### ISSUE TITLE
Problem meeting deadline

### ISSUE THREAD

**Issue by mvbarroeta** [janboone/programming-for-economists#14]
Hello, I am the student whose mac crashed last tutorial. I tried going to the Apple Store but because of Easter it was closed most of last week. I still have not been able to turn it on and therefore could not meet this past weekend's deadline. Is it possible to work on a computer from university until I manage to solve the problem with my laptop? Thank you in advance for your understanding. Best regards, Victoria Barroeta.

**Comment by clemensfiedler** [comment]
Hi Victoria,

You can also do the assignment on campus. 

In order to bring up the console on a windows PC: 
- press the win key + r
- type 'cmd' (without ' ')
- then you can run the notebook as usual ('jupyter notebook')
- Alternatively, search for console in the windows start menu.

I know that the computer in G building have python installed, but am not sure about the library.

**Comment by janboone** [comment]
for the python part of the course --but not for R-- you can also use: https://jupyter.uvt.nl
from any computer.

Can you finish the assignment by Friday and email me when you are finished?
